{**
* 2007-2018 PrestaShop
*
* NOTICE OF LICENSE
*
* @author    Innova Deluxe SL
* @copyright 2018 Innova Deluxe SL
* @license   INNOVADELUXE
*}

<div class="tab-content">
    <div role="tabpanel" class="tab-pane fade active in">
        <div class="panel">
            <div class="panel-heading">
                <i class="icon-cogs"></i> {l s='Audit cookies' mod='idxcookies'}
            </div>

            <div class="alert alert-danger">
                <h4>{l s='Important notice: Experimental Functionality' mod='idxcookies'}</h4>
                <p>{l s='The automatic cookie audit system checks the cookies generated by the shop from the home page, product category, product file, CMS page, shop section and basket page. Please note that your store may be generating cookies in other sections that are not scanned by the automated audit system. In this case you can contact us to add these sections to the audit system and publish them in the next module update.' mod='idxcookies'}</p>
                <p>{l s='It is recommended that the audit performed by the automated system be reviewed by a specialized technician to ensure that no cookies are missing. If the automatic system does not detect all the Cookies in the shop, you can add them manually from the functionality enabled for this purpose.' mod='idxcookies'}</p>
                <p>{l s='Cookies from conversion tracking systems (Facebook, Google, etc....), may not be detected by the automatic system, as these cookies generate cookies from pages outside the store that the system cannot analyze, in these cases, you will have to do a manual analysis and add by hand from the functionality that has the module for it.' mod='idxcookies'}</p>
                <p>{l s='NOTE: EXTERNAL DOMAIN COOKIES ARE NOT AUDITABLE with this functionality currently. Innovadeluxe Diseño y Desarrollo Web SL, disclaims any responsibility about it.' mod='idxcookies'}</p>
            </div>
            <div class="text-center well">
                <a class="btn btn-primary btn-lg" href="{$index_url|escape:'htmlall':'UTF-8'|htmlspecialchars_decode}">
                    <i class="icon icon-search"></i> {l s='Audit page' mod='idxcookies'}
                </a>
            </div>

        </div>
    </div>
</div>
