<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLzheb7y\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLzheb7y/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerLzheb7y.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerLzheb7y\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerLzheb7y\appProdProjectContainer([
    'container.build_hash' => 'Lzheb7y',
    'container.build_id' => '56b4c3b1',
    'container.build_time' => 1666773769,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLzheb7y');
